# Generated by Django 3.1.5 on 2021-02-17 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankID', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankidauthentication',
            name='cats',
        ),
    ]
