export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const AUTH_WAITING_BANKID = 'AUTH_START_BANKID'
export const AUTH_SUCCESS_BANKID = 'AUTH_SUCCESS_BANKID'
export const AUTH_CANCEL_BANKID = 'AUTH_CANCEL_BANKID'
export const AUTH_RESTORE_BANKID = 'AUTH_RESTORE_BANKID'
