# Generated by Django 3.1.7 on 2021-03-06 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210306_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='bank_id',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='phone_number_verified',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='street',
        ),
    ]
