# Generated by Django 3.1.7 on 2021-03-06 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankID', '0001_initial'),
        ('users', '0003_auto_20210306_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='bank_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bankID.bankidauthentication'),
        ),
    ]
