# Generated by Django 3.1.7 on 2021-03-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankIDAuthentication',
            fields=[
                ('order_ref', models.CharField(default=None, max_length=255, primary_key=True, serialize=False)),
                ('accepted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('type_of_authentication', models.CharField(choices=[('Non', 'Empty'), ('REG', 'Registration'), ('PI', 'Purchase'), ('PO', 'Payout')], default=None, max_length=3)),
            ],
        ),
    ]
