# Generated by Django 3.2 on 2021-04-11 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bankID', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankidauthentication',
            name='account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankidauthentication',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bankidauthentication',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankidauthentication',
            name='accepted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
