# Generated by Django 3.2 on 2021-04-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankID', '0002_auto_20210411_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankidauthentication',
            name='p_number',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
